/**
 * toolkit-page.ts — Renders the live hub-template features list on
 * the Hub Toolkit page from site/public/hub-template-data.json (which
 * is regenerated by scripts/fetch-hub-template-readme.ts on every
 * build).
 *
 * If the JSON is missing or empty, falls back to a small static list
 * so the page is never broken — even before the first build runs.
 */

interface HubTemplateData {
    fetchedAt: string;
    quickStart: string;
    whatYouGet: string[];
    customizationFields: Array<{ field: string; description: string }>;
    demoUrl: string;
    repoUrl: string;
    error?: string;
}

const FALLBACK: HubTemplateData = {
    fetchedAt: new Date().toISOString(),
    quickStart: "",
    whatYouGet: [
        "Learning tree — Shared curriculum rendered inline on your site.",
        "Workshops — Hands-on session content with facilitator guides.",
        "Playbooks — Operational guides for running a chapter.",
        "Events — List your club's upcoming events right in the config.",
        "Officers — Showcase your leadership team.",
        "Custom about — Write your club's story in the config — no HTML editing.",
        "Auto-deploy — Push to main and GitHub Pages deploys.",
        "Theming — Set two colors in the config and the entire site adapts.",
    ],
    customizationFields: [],
    demoUrl: "https://all-applied-ai-network.github.io/aain-hub-template/",
    repoUrl: "https://github.com/ALL-Applied-AI-Network/aain-hub-template",
};

async function loadData(): Promise<HubTemplateData> {
    try {
        const res = await fetch("./public/hub-template-data.json", {
            cache: "default",
        });
        if (!res.ok) throw new Error(`status ${res.status}`);
        const data = (await res.json()) as HubTemplateData;
        return data.whatYouGet.length > 0 ? data : FALLBACK;
    } catch (err) {
        console.warn("[toolkit] hub-template-data load failed, using fallback:", err);
        return FALLBACK;
    }
}

function escapeHtml(s: string): string {
    return s
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;");
}

/**
 * Renders the bullet list with a check icon, splitting the bold lead
 * (everything before the first em-dash) from the description.
 */
function renderItem(item: string): string {
    const dashMatch = item.match(/^(.+?)\s+[—-]\s+(.+)$/);
    const lead = dashMatch ? dashMatch[1] : item;
    const rest = dashMatch ? dashMatch[2] : "";
    return `
        <li class="hub-template-features__item">
            <span class="hub-template-features__check" aria-hidden="true">
                <svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M3.5 8.5L6.5 11.5L12.5 5.5" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
            </span>
            <div class="hub-template-features__text">
                <strong>${escapeHtml(lead)}</strong>${rest ? ` &mdash; ${escapeHtml(rest)}` : ""}
            </div>
        </li>
    `;
}

function renderUpdated(data: HubTemplateData): string {
    if (!data.fetchedAt) return "";
    let date: Date;
    try {
        date = new Date(data.fetchedAt);
    } catch {
        return "";
    }
    const stamp = `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}-${String(date.getUTCDate()).padStart(2, "0")}`;
    return `Pulled from <a href="${escapeHtml(data.repoUrl)}/blob/main/README.md" target="_blank" rel="noopener"><code>aain-hub-template/README.md</code></a> on ${stamp}.`;
}

async function init(): Promise<void> {
    // Toolkit hero: animated mesh-gradient backdrop + the brand-colored
    // particle network overlaid on top. Pure CSS for the gradient (in
    // toolkit.css), pure 2D canvas for the particles. Light, distinct
    // from the home page's 3D node-graph, gets out of the way of the
    // founder-timeline copy.
    //
    // The 3D scene mount point still exists for backwards-compat but
    // we no longer attach a Three.js renderer to it — the gradient
    // does the heavy lifting visually.
    const hero3d = document.getElementById("hero-3d");
    if (hero3d) {
        hero3d.classList.add("loaded");
    }
    const particlesCanvas = document.getElementById("hero-particles");
    if (particlesCanvas instanceof HTMLCanvasElement) {
        import("./hero-particles").then((m) =>
            m.initHeroParticles(particlesCanvas),
        );
    }

    // Timeline progress indicator: light up the active step's marker
    // in the sticky timeline track as the user scrolls.
    initTimelineProgress();

    const list = document.getElementById("hub-template-list");
    const updated = document.getElementById("hub-template-updated");
    const demo = document.getElementById(
        "hub-template-demo",
    ) as HTMLAnchorElement | null;
    const repo = document.getElementById(
        "hub-template-repo",
    ) as HTMLAnchorElement | null;

    const data = await loadData();

    if (list) {
        list.innerHTML = data.whatYouGet.map(renderItem).join("");
    }
    if (updated) {
        updated.innerHTML = renderUpdated(data);
    }
    if (demo) demo.href = data.demoUrl;
    if (repo) repo.href = data.repoUrl;
}

/**
 * Timeline progress: while the user scrolls through the four founder
 * steps, the corresponding timeline marker gets `--active` and the
 * vertical line "fills in" up to that point. Pure intersection
 * observer — no scroll listener thrash.
 */
function initTimelineProgress(): void {
    const steps = Array.from(
        document.querySelectorAll<HTMLElement>(".toolkit-step"),
    );
    const markers = Array.from(
        document.querySelectorAll<HTMLElement>(".timeline-track__marker"),
    );
    const fill = document.querySelector<HTMLElement>(".timeline-track__fill");
    if (steps.length === 0) return;

    const obs = new IntersectionObserver(
        (entries) => {
            for (const e of entries) {
                const idx = steps.indexOf(e.target as HTMLElement);
                if (idx < 0) continue;
                if (e.isIntersecting) {
                    // Activate this and all earlier markers; deactivate later
                    for (let i = 0; i < markers.length; i++) {
                        markers[i].classList.toggle(
                            "timeline-track__marker--active",
                            i <= idx,
                        );
                    }
                    if (fill) {
                        const pct = ((idx + 1) / steps.length) * 100;
                        fill.style.height = `${pct}%`;
                    }
                }
            }
        },
        { rootMargin: "-40% 0px -40% 0px", threshold: 0 },
    );
    for (const s of steps) obs.observe(s);
}

init();
